{
	"name": "second_Transform_Atb",
	"properties": {
		"description": "Transform Atb data ",
		"activities": [
			{
				"name": "Insert to cvtATB",
				"description": "Use [dbo].[usp_ConvLoad_cvtATB]",
				"type": "SqlServerStoredProcedure",
				"dependsOn": [],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"storedProcedureName": "[dbo].[usp_ConvLoad_cvtATB]"
				},
				"linkedServiceName": {
					"referenceName": "localsqldb",
					"type": "LinkedServiceReference"
				}
			},
			{
				"name": "Send mail about Fail 1",
				"description": "Send mail about Fail Insert to cvt Table",
				"type": "WebActivity",
				"dependsOn": [
					{
						"activity": "Insert to cvtATB",
						"dependencyConditions": [
							"Failed"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"url": "https://prod-36.northeurope.logic.azure.com:443/workflows/5e14d7532c934efb967b64d4eb6b97f9/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=t_y49xgm25kdUxJeG10AAWU4nZDTCzeT6rbcRlnKpGQ",
					"method": "POST",
					"body": {
						"message": "ETL process was FAILED. ATB data wasn't inserted to cvt Table. This is a custom dynamic message from your pipeline with run ID @{pipeline().RunId}.",
						"dataFactoryName": "@{pipeline().DataFactory}",
						"pipelineName": "@{pipeline().Pipeline}",
						"receiver": "@{pipeline().parameters.receiver}"
					}
				}
			},
			{
				"name": "Update Timelines from ATB",
				"description": "Use usp_Update_All_Timelines  for update Timelines dictionary",
				"type": "SqlServerStoredProcedure",
				"dependsOn": [
					{
						"activity": "Update Dictionaries from ATB",
						"dependencyConditions": [
							"Succeeded"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"storedProcedureName": "[dbo].[usp_Update_All_Timelines]",
					"storedProcedureParameters": {
						"Tbl": {
							"value": "cvtATB",
							"type": "String"
						}
					}
				},
				"linkedServiceName": {
					"referenceName": "localsqldb",
					"type": "LinkedServiceReference"
				}
			},
			{
				"name": "Send mail about Fail 3",
				"description": "Send mail about Fail update Timelines from ATB",
				"type": "WebActivity",
				"dependsOn": [
					{
						"activity": "Update Timelines from ATB",
						"dependencyConditions": [
							"Failed"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"url": "https://prod-36.northeurope.logic.azure.com:443/workflows/5e14d7532c934efb967b64d4eb6b97f9/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=t_y49xgm25kdUxJeG10AAWU4nZDTCzeT6rbcRlnKpGQ",
					"method": "POST",
					"body": {
						"message": "ETL process was FAILED.  Updating Timelines from ATB was FAILED. This is a custom dynamic message from your pipeline with run ID @{pipeline().RunId}.",
						"dataFactoryName": "@{pipeline().DataFactory}",
						"pipelineName": "@{pipeline().Pipeline}",
						"receiver": "@{pipeline().parameters.receiver}"
					}
				}
			},
			{
				"name": "Update Dictionaries from ATB",
				"description": "Use [dbo].[usp_Update_All_Dictionaries] for update Dictionaries from ATB",
				"type": "SqlServerStoredProcedure",
				"dependsOn": [
					{
						"activity": "Insert to cvtATB",
						"dependencyConditions": [
							"Succeeded"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"storedProcedureName": "[dbo].[usp_Update_All_Dictionaries]",
					"storedProcedureParameters": {
						"Tbl": {
							"value": "cvtATB",
							"type": "String"
						}
					}
				},
				"linkedServiceName": {
					"referenceName": "localsqldb",
					"type": "LinkedServiceReference"
				}
			},
			{
				"name": "Send mail about Fail 2",
				"description": "Send mail about Fail update Dictionaries  from ATB",
				"type": "WebActivity",
				"dependsOn": [
					{
						"activity": "Update Dictionaries from ATB",
						"dependencyConditions": [
							"Failed"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"url": "https://prod-36.northeurope.logic.azure.com:443/workflows/5e14d7532c934efb967b64d4eb6b97f9/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=t_y49xgm25kdUxJeG10AAWU4nZDTCzeT6rbcRlnKpGQ",
					"method": "POST",
					"body": {
						"message": "ETL process was FAILED.   Updating Dictionaries from ATB was FAILED. This is a custom dynamic message from your pipeline with run ID @{pipeline().RunId}.",
						"dataFactoryName": "@{pipeline().DataFactory}",
						"pipelineName": "@{pipeline().Pipeline}",
						"receiver": "@{pipeline().parameters.receiver}"
					}
				}
			},
			{
				"name": "Update cvtATB",
				"description": "Update cvtATB according to dictionaries \nuse [dbo].[usp_ConvModify_ATB]",
				"type": "SqlServerStoredProcedure",
				"dependsOn": [
					{
						"activity": "Update Timelines from ATB",
						"dependencyConditions": [
							"Succeeded"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"storedProcedureName": "[dbo].[usp_ConvModify_ATB]"
				},
				"linkedServiceName": {
					"referenceName": "localsqldb",
					"type": "LinkedServiceReference"
				}
			},
			{
				"name": "Send mail about Fail 4",
				"description": "Send mail about Fail update cvtATB",
				"type": "WebActivity",
				"dependsOn": [
					{
						"activity": "Update cvtATB",
						"dependencyConditions": [
							"Failed"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"url": "https://prod-36.northeurope.logic.azure.com:443/workflows/5e14d7532c934efb967b64d4eb6b97f9/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=t_y49xgm25kdUxJeG10AAWU4nZDTCzeT6rbcRlnKpGQ",
					"method": "POST",
					"body": {
						"message": "ETL process was FAILED.  Updating cvtATB was FAILED. This is a custom dynamic message from your pipeline with run ID @{pipeline().RunId}.",
						"dataFactoryName": "@{pipeline().DataFactory}",
						"pipelineName": "@{pipeline().Pipeline}",
						"receiver": "@{pipeline().parameters.receiver}"
					}
				}
			},
			{
				"name": "Update RetainZero in cvtATB",
				"description": "Update RetainZero in cvtATB use [dbo].[usp_Dimension_Retain_Zero]",
				"type": "SqlServerStoredProcedure",
				"dependsOn": [
					{
						"activity": "Update cvtATB",
						"dependencyConditions": [
							"Succeeded"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"storedProcedureName": "[dbo].[usp_Dimension_Retain_Zero]"
				},
				"linkedServiceName": {
					"referenceName": "localsqldb",
					"type": "LinkedServiceReference"
				}
			},
			{
				"name": "Send mail about Fail 5",
				"description": "Send mail about Fail update RetainZero \n in cvtATB",
				"type": "WebActivity",
				"dependsOn": [
					{
						"activity": "Update RetainZero in cvtATB",
						"dependencyConditions": [
							"Failed"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"url": "https://prod-36.northeurope.logic.azure.com:443/workflows/5e14d7532c934efb967b64d4eb6b97f9/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=t_y49xgm25kdUxJeG10AAWU4nZDTCzeT6rbcRlnKpGQ",
					"method": "POST",
					"body": {
						"message": "ETL process was FAILED.  Updating RetainZero in cvtATB was FAILED. This is a custom dynamic message from your pipeline with run ID @{pipeline().RunId}.",
						"dataFactoryName": "@{pipeline().DataFactory}",
						"pipelineName": "@{pipeline().Pipeline}",
						"receiver": "@{pipeline().parameters.receiver}"
					}
				}
			},
			{
				"name": "Update RetainZero in cvtATB step2",
				"description": "Update RetainZero in cvtATB use  [dbo].[usp_Retain_Zero] for CurrentBalance=0 ",
				"type": "SqlServerStoredProcedure",
				"dependsOn": [
					{
						"activity": "Update RetainZero in cvtATB",
						"dependencyConditions": [
							"Succeeded"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"storedProcedureName": "[dbo].[usp_Retain_Zero]"
				},
				"linkedServiceName": {
					"referenceName": "localsqldb",
					"type": "LinkedServiceReference"
				}
			},
			{
				"name": "Send mail about Fail 6",
				"description": "Send mail about Fail update RetainZero for CurrentBalance=0 ",
				"type": "WebActivity",
				"dependsOn": [
					{
						"activity": "Update RetainZero in cvtATB step2",
						"dependencyConditions": [
							"Failed"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"url": "https://prod-36.northeurope.logic.azure.com:443/workflows/5e14d7532c934efb967b64d4eb6b97f9/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=t_y49xgm25kdUxJeG10AAWU4nZDTCzeT6rbcRlnKpGQ",
					"method": "POST",
					"body": {
						"message": "ETL process was FAILED.  Updating RetainZero in cvtATB was FAILED for CurrentBalance=0 . This is a custom dynamic message from your pipeline with run ID @{pipeline().RunId}.",
						"dataFactoryName": "@{pipeline().DataFactory}",
						"pipelineName": "@{pipeline().Pipeline}",
						"receiver": "@{pipeline().parameters.receiver}"
					}
				}
			},
			{
				"name": "Update Age by Dates in cvtATB",
				"description": "Update Age by Dates in cvtATB use  [dbo].[usp_UpdateAge_ATB]",
				"type": "SqlServerStoredProcedure",
				"dependsOn": [
					{
						"activity": "Update RetainZero in cvtATB step2",
						"dependencyConditions": [
							"Succeeded"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"storedProcedureName": "[dbo].[usp_UpdateAge_ATB]"
				},
				"linkedServiceName": {
					"referenceName": "localsqldb",
					"type": "LinkedServiceReference"
				}
			},
			{
				"name": "Send mail about Fail 7",
				"description": "Send mail about Fail update  Age by Dates in cvtATB ",
				"type": "WebActivity",
				"dependsOn": [
					{
						"activity": "Update Age by Dates in cvtATB",
						"dependencyConditions": [
							"Failed"
						]
					}
				],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"url": "https://prod-36.northeurope.logic.azure.com:443/workflows/5e14d7532c934efb967b64d4eb6b97f9/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=t_y49xgm25kdUxJeG10AAWU4nZDTCzeT6rbcRlnKpGQ",
					"method": "POST",
					"body": {
						"message": "ETL process was FAILED.  Updating  Age by Dates in cvtATB was FAILED. This is a custom dynamic message from your pipeline with run ID @{pipeline().RunId}.",
						"dataFactoryName": "@{pipeline().DataFactory}",
						"pipelineName": "@{pipeline().Pipeline}",
						"receiver": "@{pipeline().parameters.receiver}"
					}
				}
			}
		],
		"parameters": {
			"receiver": {
				"type": "string",
				"defaultValue": "alina_parkhomenko@epam.com"
			},
			"TBL": {
				"type": "string",
				"defaultValue": "cvtATB"
			}
		},
		"folder": {
			"name": "ETL"
		},
		"annotations": []
	}
}